development:
  adapter: postgresql
  encoding: unicode
  database: xml_parser_etpgpb_ru_development
  pool: 5
  username: postgres
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: xml_parser_etpgpb_ru_test
  pool: 5
  username: postgres
  host: 127.0.0.1
